scenario:
  name: hetero_10v10
  task: T1_air_superiority
  physics_hz: 20
  max_steps: 6000
  win_conditions:
    annihilation: true
  red:
    formation: spread
    scripted_level: L2
    platforms:
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - ov10_ucav
    - ov10_ucav
    - ov10_ucav
    spawn:
    - - -1800
      - -16200
      - -3500
      - 1.5708
      - 230
    - - -1200
      - -15800
      - -3550
      - 1.5708
      - 230
    - - -600
      - -15400
      - -3600
      - 1.5708
      - 230
    - - 0
      - -15000
      - -3500
      - 1.5708
      - 230
    - - 600
      - -15400
      - -3550
      - 1.5708
      - 230
    - - 1200
      - -15800
      - -3600
      - 1.5708
      - 230
    - - 1800
      - -16200
      - -3500
      - 1.5708
      - 230
    - - -1200
      - -16200
      - -3450
      - 1.5708
      - 70
    - - -1800
      - -16600
      - -3450
      - 1.5708
      - 70
    - - -2400
      - -17000
      - -3450
      - 1.5708
      - 70
    jitter_m:
    - 300
    - 200
    - 100
  blue:
    formation: wedge
    difficulty: L2
    platforms:
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    - f16_fighter
    spawn:
    - - -2700.0
      - 16800.0
      - -3500
      - -1.4707999999999999
      - 230
    - - -2100.0
      - 16400.0
      - -3550
      - -1.5208
      - 230
    - - -1500.0
      - 16000.0
      - -3600
      - -1.5708
      - 230
    - - -900.0
      - 15600.0
      - -3500
      - -1.6208
      - 230
    - - -300.0
      - 15200.0
      - -3550
      - -1.6708
      - 230
    - - 300.0
      - 15200.0
      - -3600
      - -1.4707999999999999
      - 230
    - - 900.0
      - 15600.0
      - -3500
      - -1.5208
      - 230
    - - 1500.0
      - 16000.0
      - -3550
      - -1.5708
      - 230
    - - 2100.0
      - 16400.0
      - -3600
      - -1.6208
      - 230
    - - 2700.0
      - 16800.0
      - -3500
      - -1.6708
      - 230
    jitter_m:
    - 300
    - 200
    - 100
  arena:
    floor_m: 30.0
    ceiling_m: 16000.0
    disengage_range_m: 60000.0
